// This file is auto-generated by @hey-api/openapi-ts

export const ErrorResponseSchema = {
  type: "object",
  properties: {
    error: {
      type: "string",
      example: "Error message details",
    },
  },
} as const;

export const PredictionResultSchema = {
  type: "object",
  properties: {
    prediction: {
      type: "string",
      description: "The predicted label category.",
      example: "Offensive",
    },
    label: {
      type: "string",
      description: "Normalized label in lower case.",
      enum: ["normal", "offensive", "hate_speech"],
      example: "offensive",
    },
    label_id: {
      type: "integer",
      description:
        "Code ID representing the prediction (0 = Normal, 1 = Offensive, 2 = Hate Speech).",
      example: 1,
    },
    is_suspicious: {
      type: "boolean",
      description: "True if label is Offensive or Hate Speech.",
      example: true,
    },
    warning_level: {
      type: "string",
      description: "Risk-level classification based on prediction details.",
      enum: ["none", "low", "medium", "high"],
      example: "medium",
    },
    confidence_scores: {
      type: "object",
      properties: {
        normal: {
          type: "number",
          format: "float",
          example: 0.125,
        },
        offensive: {
          type: "number",
          format: "float",
          example: 0.812,
        },
        hate_speech: {
          type: "number",
          format: "float",
          example: 0.063,
        },
      },
    },
    original_text: {
      type: "string",
      example: "Stupid jerk, get out!",
    },
    preprocessed_text: {
      type: "string",
      example: "stupid jerk get out",
    },
    detection_method: {
      type: "string",
      description: "How the prediction was computed.",
      example: "ml_model",
    },
    matched_keyword: {
      type: "string",
      nullable: true,
      example: null,
    },
  },
} as const;

export const StrikeSchema = {
  type: "object",
  properties: {
    id: {
      type: "integer",
      example: 1,
    },
    user_id: {
      type: "string",
      example: "1234567890",
    },
    username: {
      type: "string",
      example: "JohnDoe",
    },
    message: {
      type: "string",
      example: "This is bad text",
    },
    warning_level: {
      type: "string",
      example: "medium",
    },
    timestamp: {
      type: "string",
      format: "date-time",
      example: "2026-07-07T18:27:48.123456",
    },
    action_taken: {
      type: "string",
      example: "warning",
    },
    reviewed: {
      type: "boolean",
      example: false,
    },
    hate_score: {
      type: "number",
      format: "float",
      example: 0.05,
    },
    offensive_score: {
      type: "number",
      format: "float",
      example: 0.91,
    },
    detection_method: {
      type: "string",
      example: "ml_model",
    },
    matched_keyword: {
      type: "string",
      nullable: true,
      example: null,
    },
  },
} as const;

export const UserSchema = {
  type: "object",
  properties: {
    username: {
      type: "string",
      example: "JohnDoe",
    },
    strikes: {
      type: "integer",
      example: 3,
    },
    warnings: {
      type: "integer",
      example: 0,
    },
    status: {
      type: "string",
      enum: ["active", "warned", "suspended", "banned"],
      example: "active",
    },
    last_seen: {
      type: "string",
      format: "date-time",
      example: "2026-07-07T18:27:48.123456",
    },
    high_strikes: {
      type: "integer",
      example: 1,
    },
    medium_strikes: {
      type: "integer",
      example: 2,
    },
  },
} as const;

export const UserStrikesInfoSchema = {
  type: "object",
  properties: {
    strikes: {
      type: "integer",
      example: 3,
    },
    warnings: {
      type: "integer",
      example: 1,
    },
    status: {
      type: "string",
      example: "active",
    },
    high_strikes: {
      type: "integer",
      example: 1,
    },
    medium_strikes: {
      type: "integer",
      example: 2,
    },
  },
} as const;
