// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-axios';
import type { Get_Data, Get_Response, GetHealth_Data, GetHealth_Response, PostPredict_Data, PostPredict_Response, PostPredict_Error, GetApiStrikes_Data, GetApiStrikes_Response, GetApiStrikes_Error, PostApiStrikes_Data, PostApiStrikes_Response, PostApiStrikes_Error, PutApiStrikesByStrikeIdReview_Data, PutApiStrikesByStrikeIdReview_Response, PutApiStrikesByStrikeIdReview_Error, DeleteApiStrikesByStrikeId_Data, DeleteApiStrikesByStrikeId_Response, DeleteApiStrikesByStrikeId_Error, GetApiUsers_Data, GetApiUsers_Response, GetApiUsers_Error, PutApiUsersByUserIdStatus_Data, PutApiUsersByUserIdStatus_Response, PutApiUsersByUserIdStatus_Error, GetApiUsersByUserIdStrikes_Data, GetApiUsersByUserIdStrikes_Response, GetApiUsersByUserIdStrikes_Error, GetApiStats_Data, GetApiStats_Response, GetApiStats_Error, GetApiDbStatus_Data, GetApiDbStatus_Response, GetApiDbStatus_Error, GetApiTest_Data, GetApiTest_Response, GetApiTestSave_Data, GetApiTestSave_Response, GetApiTestSave_Error, GetAdmin_Data, GetAdmin_Response, GetTest_Data, GetTest_Response } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
};

export class DefaultService {
    /**
     * API Information
     * Returns general status and list of available endpoints.
     */
    public static get<ThrowOnError extends boolean = false>(options?: Options<Get_Data, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<Get_Response, unknown, ThrowOnError>({
            url: '/',
            ...options
        });
    }
    
    /**
     * Health Check
     * Returns health status of the API and SQLite database.
     */
    public static getHealth<ThrowOnError extends boolean = false>(options?: Options<GetHealth_Data, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetHealth_Response, unknown, ThrowOnError>({
            url: '/health',
            ...options
        });
    }
    
    /**
     * Analyze Text
     * Analyzes a given text to classify it as Normal, Offensive, or Hate Speech.
     * If `user_id` and `username` are provided and the warning level is "medium" or "high",
     * a strike is automatically logged in the database for that user.
     *
     */
    public static postPredict<ThrowOnError extends boolean = false>(options: Options<PostPredict_Data, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<PostPredict_Response, PostPredict_Error, ThrowOnError>({
            url: '/predict',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Get All Strikes
     * Retrieves a list of all logged moderation strikes, up to a limit of 200.
     */
    public static getApiStrikes<ThrowOnError extends boolean = false>(options?: Options<GetApiStrikes_Data, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetApiStrikes_Response, GetApiStrikes_Error, ThrowOnError>({
            url: '/api/strikes',
            ...options
        });
    }
    
    /**
     * Add Strike Manually
     * Manually adds a moderation strike for a user and updates their status in the database.
     */
    public static postApiStrikes<ThrowOnError extends boolean = false>(options: Options<PostApiStrikes_Data, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<PostApiStrikes_Response, PostApiStrikes_Error, ThrowOnError>({
            url: '/api/strikes',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Mark Strike as Reviewed
     * Marks a specific strike as reviewed (flagging it as dealt with).
     */
    public static putApiStrikesByStrikeIdReview<ThrowOnError extends boolean = false>(options: Options<PutApiStrikesByStrikeIdReview_Data, ThrowOnError>) {
        return (options.client ?? _heyApiClient).put<PutApiStrikesByStrikeIdReview_Response, PutApiStrikesByStrikeIdReview_Error, ThrowOnError>({
            url: '/api/strikes/{strike_id}/review',
            ...options
        });
    }
    
    /**
     * Delete Strike
     * Deletes a specific strike from the moderation database.
     */
    public static deleteApiStrikesByStrikeId<ThrowOnError extends boolean = false>(options: Options<DeleteApiStrikesByStrikeId_Data, ThrowOnError>) {
        return (options.client ?? _heyApiClient).delete<DeleteApiStrikesByStrikeId_Response, DeleteApiStrikesByStrikeId_Error, ThrowOnError>({
            url: '/api/strikes/{strike_id}',
            ...options
        });
    }
    
    /**
     * Get All Users
     * Retrieves all tracked users from the database, ordered by total strikes descending.
     */
    public static getApiUsers<ThrowOnError extends boolean = false>(options?: Options<GetApiUsers_Data, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetApiUsers_Response, GetApiUsers_Error, ThrowOnError>({
            url: '/api/users',
            ...options
        });
    }
    
    /**
     * Update User Status
     * Updates the moderation status (e.g. active, warned, suspended, banned) of a specific user.
     */
    public static putApiUsersByUserIdStatus<ThrowOnError extends boolean = false>(options: Options<PutApiUsersByUserIdStatus_Data, ThrowOnError>) {
        return (options.client ?? _heyApiClient).put<PutApiUsersByUserIdStatus_Response, PutApiUsersByUserIdStatus_Error, ThrowOnError>({
            url: '/api/users/{user_id}/status',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Get User Moderation Status
     * Retrieves the strikes, warnings, status, and category counts for a specific user.
     */
    public static getApiUsersByUserIdStrikes<ThrowOnError extends boolean = false>(options: Options<GetApiUsersByUserIdStrikes_Data, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<GetApiUsersByUserIdStrikes_Response, GetApiUsersByUserIdStrikes_Error, ThrowOnError>({
            url: '/api/users/{user_id}/strikes',
            ...options
        });
    }
    
    /**
     * Get Overall Statistics
     * Returns counts of total strikes, high/medium/low risk strikes, reviewed status, and total users.
     */
    public static getApiStats<ThrowOnError extends boolean = false>(options?: Options<GetApiStats_Data, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetApiStats_Response, GetApiStats_Error, ThrowOnError>({
            url: '/api/stats',
            ...options
        });
    }
    
    /**
     * Check Database Status
     * Returns database file existence, size, list of tables, and path.
     */
    public static getApiDbStatus<ThrowOnError extends boolean = false>(options?: Options<GetApiDbStatus_Data, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetApiDbStatus_Response, GetApiDbStatus_Error, ThrowOnError>({
            url: '/api/db-status',
            ...options
        });
    }
    
    /**
     * Test API
     * Simple endpoint to test if the API is active.
     */
    public static getApiTest<ThrowOnError extends boolean = false>(options?: Options<GetApiTest_Data, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetApiTest_Response, unknown, ThrowOnError>({
            url: '/api/test',
            ...options
        });
    }
    
    /**
     * Test Save Data
     * Inserts mock test data to the database to ensure write operations work.
     */
    public static getApiTestSave<ThrowOnError extends boolean = false>(options?: Options<GetApiTestSave_Data, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetApiTestSave_Response, GetApiTestSave_Error, ThrowOnError>({
            url: '/api/test-save',
            ...options
        });
    }
    
    /**
     * Serve Admin Dashboard
     * Returns the static HTML administration dashboard.
     */
    public static getAdmin<ThrowOnError extends boolean = false>(options?: Options<GetAdmin_Data, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetAdmin_Response, unknown, ThrowOnError>({
            responseType: 'text',
            url: '/admin',
            ...options
        });
    }
    
    /**
     * Serve Test Page
     * Returns the static HTML text prediction interface.
     */
    public static getTest<ThrowOnError extends boolean = false>(options?: Options<GetTest_Data, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetTest_Response, unknown, ThrowOnError>({
            responseType: 'text',
            url: '/test',
            ...options
        });
    }
    
}