// This file is auto-generated by @hey-api/openapi-ts

export type ErrorResponse = {
    error?: string;
};

export type PredictionResult = {
    /**
     * The predicted label category.
     */
    prediction?: string;
    /**
     * Normalized label in lower case.
     */
    label?: 'normal' | 'offensive' | 'hate_speech';
    /**
     * Code ID representing the prediction (0 = Normal, 1 = Offensive, 2 = Hate Speech).
     */
    label_id?: number;
    /**
     * True if label is Offensive or Hate Speech.
     */
    is_suspicious?: boolean;
    /**
     * Risk-level classification based on prediction details.
     */
    warning_level?: 'none' | 'low' | 'medium' | 'high';
    confidence_scores?: {
        normal?: number;
        offensive?: number;
        hate_speech?: number;
    };
    original_text?: string;
    preprocessed_text?: string;
    /**
     * How the prediction was computed.
     */
    detection_method?: string;
    matched_keyword?: string | null;
};

export type Strike = {
    id?: number;
    user_id?: string;
    username?: string;
    message?: string;
    warning_level?: string;
    timestamp?: string;
    action_taken?: string;
    reviewed?: boolean;
    hate_score?: number;
    offensive_score?: number;
    detection_method?: string;
    matched_keyword?: string | null;
};

export type User = {
    username?: string;
    strikes?: number;
    warnings?: number;
    status?: 'active' | 'warned' | 'suspended' | 'banned';
    last_seen?: string;
    high_strikes?: number;
    medium_strikes?: number;
};

export type UserStrikesInfo = {
    strikes?: number;
    warnings?: number;
    status?: string;
    high_strikes?: number;
    medium_strikes?: number;
};

export type Get_Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type Get_Responses = {
    /**
     * Successful Response
     */
    200: {
        status?: string;
        message?: string;
        version?: string;
        endpoints?: {
            [key: string]: string;
        };
    };
};

export type Get_Response = Get_Responses[keyof Get_Responses];

export type GetHealth_Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealth_Responses = {
    /**
     * Successful Response
     */
    200: {
        status?: string;
        database?: string;
        database_file?: string;
        timestamp?: string;
    };
};

export type GetHealth_Response = GetHealth_Responses[keyof GetHealth_Responses];

export type PostPredict_Data = {
    body: {
        /**
         * The text message to analyze.
         */
        text: string;
        /**
         * Optional Discord/platform user ID to track strikes.
         */
        user_id?: string;
        /**
         * Optional platform username.
         */
        username?: string;
    };
    path?: never;
    query?: never;
    url: '/predict';
};

export type PostPredict_Errors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type PostPredict_Error = PostPredict_Errors[keyof PostPredict_Errors];

export type PostPredict_Responses = {
    /**
     * Analysis Result
     */
    200: PredictionResult;
};

export type PostPredict_Response = PostPredict_Responses[keyof PostPredict_Responses];

export type GetApiStrikes_Data = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Maximum number of strikes to retrieve.
         */
        limit?: number;
    };
    url: '/api/strikes';
};

export type GetApiStrikes_Errors = {
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetApiStrikes_Error = GetApiStrikes_Errors[keyof GetApiStrikes_Errors];

export type GetApiStrikes_Responses = {
    /**
     * A list of strikes
     */
    200: {
        total?: number;
        strikes?: Array<Strike>;
    };
};

export type GetApiStrikes_Response = GetApiStrikes_Responses[keyof GetApiStrikes_Responses];

export type PostApiStrikes_Data = {
    body: {
        user_id: string;
        username: string;
        message: string;
        warning_level: 'low' | 'medium' | 'high';
        action_taken?: string;
        hate_score?: number;
        offensive_score?: number;
        detection_method?: string;
        matched_keyword?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/strikes';
};

export type PostApiStrikes_Errors = {
    /**
     * Missing required fields
     */
    400: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type PostApiStrikes_Error = PostApiStrikes_Errors[keyof PostApiStrikes_Errors];

export type PostApiStrikes_Responses = {
    /**
     * Strike added successfully
     */
    200: {
        status?: string;
        message?: string;
    };
};

export type PostApiStrikes_Response = PostApiStrikes_Responses[keyof PostApiStrikes_Responses];

export type PutApiStrikesByStrikeIdReview_Data = {
    body?: never;
    path: {
        /**
         * The numeric ID of the strike.
         */
        strike_id: number;
    };
    query?: never;
    url: '/api/strikes/{strike_id}/review';
};

export type PutApiStrikesByStrikeIdReview_Errors = {
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type PutApiStrikesByStrikeIdReview_Error = PutApiStrikesByStrikeIdReview_Errors[keyof PutApiStrikesByStrikeIdReview_Errors];

export type PutApiStrikesByStrikeIdReview_Responses = {
    /**
     * Strike marked as reviewed
     */
    200: {
        status?: string;
        message?: string;
    };
};

export type PutApiStrikesByStrikeIdReview_Response = PutApiStrikesByStrikeIdReview_Responses[keyof PutApiStrikesByStrikeIdReview_Responses];

export type DeleteApiStrikesByStrikeId_Data = {
    body?: never;
    path: {
        /**
         * The numeric ID of the strike.
         */
        strike_id: number;
    };
    query?: never;
    url: '/api/strikes/{strike_id}';
};

export type DeleteApiStrikesByStrikeId_Errors = {
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type DeleteApiStrikesByStrikeId_Error = DeleteApiStrikesByStrikeId_Errors[keyof DeleteApiStrikesByStrikeId_Errors];

export type DeleteApiStrikesByStrikeId_Responses = {
    /**
     * Strike deleted
     */
    200: {
        status?: string;
        message?: string;
    };
};

export type DeleteApiStrikesByStrikeId_Response = DeleteApiStrikesByStrikeId_Responses[keyof DeleteApiStrikesByStrikeId_Responses];

export type GetApiUsers_Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type GetApiUsers_Errors = {
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetApiUsers_Error = GetApiUsers_Errors[keyof GetApiUsers_Errors];

export type GetApiUsers_Responses = {
    /**
     * Successful response
     */
    200: {
        total?: number;
        users?: {
            [key: string]: User;
        };
    };
};

export type GetApiUsers_Response = GetApiUsers_Responses[keyof GetApiUsers_Responses];

export type PutApiUsersByUserIdStatus_Data = {
    body: {
        status: 'active' | 'warned' | 'suspended' | 'banned';
    };
    path: {
        /**
         * The platform user ID.
         */
        user_id: string;
    };
    query?: never;
    url: '/api/users/{user_id}/status';
};

export type PutApiUsersByUserIdStatus_Errors = {
    /**
     * Invalid request body (missing status or invalid enum value)
     */
    400: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type PutApiUsersByUserIdStatus_Error = PutApiUsersByUserIdStatus_Errors[keyof PutApiUsersByUserIdStatus_Errors];

export type PutApiUsersByUserIdStatus_Responses = {
    /**
     * User status updated successfully
     */
    200: {
        status?: string;
        message?: string;
    };
};

export type PutApiUsersByUserIdStatus_Response = PutApiUsersByUserIdStatus_Responses[keyof PutApiUsersByUserIdStatus_Responses];

export type GetApiUsersByUserIdStrikes_Data = {
    body?: never;
    path: {
        /**
         * The platform user ID.
         */
        user_id: string;
    };
    query?: never;
    url: '/api/users/{user_id}/strikes';
};

export type GetApiUsersByUserIdStrikes_Errors = {
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetApiUsersByUserIdStrikes_Error = GetApiUsersByUserIdStrikes_Errors[keyof GetApiUsersByUserIdStrikes_Errors];

export type GetApiUsersByUserIdStrikes_Responses = {
    /**
     * Successful response
     */
    200: UserStrikesInfo;
};

export type GetApiUsersByUserIdStrikes_Response = GetApiUsersByUserIdStrikes_Responses[keyof GetApiUsersByUserIdStrikes_Responses];

export type GetApiStats_Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/stats';
};

export type GetApiStats_Errors = {
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetApiStats_Error = GetApiStats_Errors[keyof GetApiStats_Errors];

export type GetApiStats_Responses = {
    /**
     * Successful response
     */
    200: {
        total_strikes?: number;
        high?: number;
        medium?: number;
        low?: number;
        reviewed?: number;
        total_users?: number;
        pending?: number;
    };
};

export type GetApiStats_Response = GetApiStats_Responses[keyof GetApiStats_Responses];

export type GetApiDbStatus_Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/db-status';
};

export type GetApiDbStatus_Errors = {
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetApiDbStatus_Error = GetApiDbStatus_Errors[keyof GetApiDbStatus_Errors];

export type GetApiDbStatus_Responses = {
    /**
     * Database status information
     */
    200: {
        exists?: boolean;
        path?: string;
        size_bytes?: number;
        size_kb?: number;
        tables?: Array<string>;
        message?: string;
    };
};

export type GetApiDbStatus_Response = GetApiDbStatus_Responses[keyof GetApiDbStatus_Responses];

export type GetApiTest_Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/test';
};

export type GetApiTest_Responses = {
    /**
     * Successful response
     */
    200: {
        status?: string;
        message?: string;
        timestamp?: string;
    };
};

export type GetApiTest_Response = GetApiTest_Responses[keyof GetApiTest_Responses];

export type GetApiTestSave_Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/test-save';
};

export type GetApiTestSave_Errors = {
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
};

export type GetApiTestSave_Error = GetApiTestSave_Errors[keyof GetApiTestSave_Errors];

export type GetApiTestSave_Responses = {
    /**
     * Test data saved successfully
     */
    200: {
        status?: string;
        message?: string;
    };
};

export type GetApiTestSave_Response = GetApiTestSave_Responses[keyof GetApiTestSave_Responses];

export type GetAdmin_Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin';
};

export type GetAdmin_Responses = {
    /**
     * HTML page
     */
    200: string;
};

export type GetAdmin_Response = GetAdmin_Responses[keyof GetAdmin_Responses];

export type GetTest_Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/test';
};

export type GetTest_Responses = {
    /**
     * HTML page
     */
    200: string;
};

export type GetTest_Response = GetTest_Responses[keyof GetTest_Responses];

export type ClientOptions = {
    baseURL: 'https://monitoring-suspicious-discussions-on-online-plat-production.up.railway.app' | 'http://localhost:5000' | (string & {});
};