/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppMessagesRouteImport } from './routes/_app.messages'
import { Route as AppDiscordBotRouteImport } from './routes/_app.discord-bot'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppApiTesterRouteImport } from './routes/_app.api-tester'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscordBotRoute = AppDiscordBotRouteImport.update({
  id: '/discord-bot',
  path: '/discord-bot',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppApiTesterRoute = AppApiTesterRouteImport.update({
  id: '/api-tester',
  path: '/api-tester',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AppAnalyticsRoute
  '/api-tester': typeof AppApiTesterRoute
  '/dashboard': typeof AppDashboardRoute
  '/discord-bot': typeof AppDiscordBotRoute
  '/messages': typeof AppMessagesRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AppAnalyticsRoute
  '/api-tester': typeof AppApiTesterRoute
  '/dashboard': typeof AppDashboardRoute
  '/discord-bot': typeof AppDiscordBotRoute
  '/messages': typeof AppMessagesRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/api-tester': typeof AppApiTesterRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/discord-bot': typeof AppDiscordBotRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/users': typeof AppUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/api-tester'
    | '/dashboard'
    | '/discord-bot'
    | '/messages'
    | '/settings'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/api-tester'
    | '/dashboard'
    | '/discord-bot'
    | '/messages'
    | '/settings'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/analytics'
    | '/_app/api-tester'
    | '/_app/dashboard'
    | '/_app/discord-bot'
    | '/_app/messages'
    | '/_app/settings'
    | '/_app/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discord-bot': {
      id: '/_app/discord-bot'
      path: '/discord-bot'
      fullPath: '/discord-bot'
      preLoaderRoute: typeof AppDiscordBotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/api-tester': {
      id: '/_app/api-tester'
      path: '/api-tester'
      fullPath: '/api-tester'
      preLoaderRoute: typeof AppApiTesterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppApiTesterRoute: typeof AppApiTesterRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDiscordBotRoute: typeof AppDiscordBotRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppApiTesterRoute: AppApiTesterRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDiscordBotRoute: AppDiscordBotRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
